import type {Metadata} from "next";
import {Quicksand} from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({
	variable: "--font-quicksand",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "...News",
	description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
	return (
		<html
			lang="en"
			className={`${quicksand.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">
				{children}
			</body>
		</html>
	);
}
