import type { Metadata } from "next";
import {Quicksand} from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${quicksand.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          <nav>
            <a href={"#"}>...news</a>
            <ul className={"flex gap-4 "}>
              <li><a href={"#"}>Nyheder</a></li>
              <li><a href={"#"}>Sport</a></li>
              <li><a href={"#"}>Vejret</a></li>
              <li><a href={"#"}>Podcast</a></li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
